### ISSUE TITLE
writer harness running twice

### ISSUE THREAD

**Issue by NikLeberg** [hgarrereyn/GraphFuzz#11]
Hi @hgarrereyn,
as mentioned in pr [#9 (comment)](https://github.com/hgarrereyn/GraphFuzz/pull/9#issuecomment-1153002342), sometimes the writer gets run twice because libFuzzer somehow thinks a memory leak happened. With an additional command line argument `-detect_leaks=0` this can be disabled.

The idea now was to set this flag automatically for a writer harness. We can manipulate `argc` and `argv` to always have this flag. For this I have modified the `SHIM_HEADER_WRITE` template in `gen_cpp.py` e.g. the `global_init(int *argc, char ***argv)` function to read the following:
```cpp
extern "C" void __attribute__((visibility ("default"))) global_init(int *argc, char ***argv) {{
    char **new_argv = (char **)malloc((*argc + 2) * sizeof(char *));
    memcpy(new_argv, *argv, sizeof(*new_argv) * *argc);
    new_argv[*argc] = (char *)"-detect_leaks=0";
    new_argv[*argc + 1] = 0;
    (*argc)++;
    *argv = new_argv;
}}
```
It feels a bit ugly and could maybe be improved with some C++ skills, but I only really know C.

What do you think about such an approach?

**Comment by hgarrereyn** [comment]
Hey, this looks pretty reasonable to me, happy to merge this if you submit a PR!
