### ISSUE TITLE
Some questions about GraphFuzz paper

### ISSUE THREAD

**Issue by icy17** [hgarrereyn/GraphFuzz#13]
Hi! I just read the paper, and I have some questions. 
1.Is the initial **corpus** mentioned in this paper a snippet of code? And How to get the corpus?
2.I noticed that in **Limitation Section**, GraphFuzz can't automatically find out which parameter is input, and which is output. So I'm a little confused about how the input and output in the **endpoint driver specification** are generated, Manual?

Looking forward to your reply!

**Comment by thuanpv** [comment]
Hi. I am also interested in the answers for these two questions. It would be great if the issue can be re-opened and answered. Thanks!

**Comment by NikLeberg** [comment]
About your first question: GraphFuzz is based on [libfuzzer](https://llvm.org/docs/LibFuzzer.html) and uses its corpus mechanism. See [this Google](https://github.com/google/fuzzing/blob/master/tutorial/libFuzzerTutorial.md#seed-corpus) tutorial that explains it a bit. Basically it is the representation that GraphFuzz uses internally that is the corpus. If I'm not mistaken then this is a binary protocol buffer (protobuf).
I generate the corpus with 'old' runs of GrapflhFuzz itself. I run it, stop it after some time, collect the generated files and use those as corpus for the next run.
Hope this helps!
