### ISSUE TITLE
terminate called after throwing an instance of 'nlohmann::detail::type_error'   what():  [json.exception.type_error.302] type must be number, but is null

### ISSUE THREAD

**Issue by CodeLogicError** [hgarrereyn/GraphFuzz#6]
when i want to run a demo have two class ,it have a bug . it might json file wrong but i don't know how to fix it.
there are my .yaml file and .h file .
[test.zip](https://github.com/hgarrereyn/GraphFuzz/files/8660451/test.zip)

**Comment by hgarrereyn** [comment]
Hi, I was able to generate a fuzzer with the files you provided:

```
# gfuzz gen cpp schema.yaml .

[Results]:
- Parsed 4 / 4 (100.0%)
- Generated 4 / 4 (100.0%)
```

```
# clang++ -o fuzz_exec fuzz_exec.cpp -fsanitize=address,fuzzer -lgraphfuzz -lprotobuf
```

```
# ./fuzz_exec
[*] Loading: schema.json
[*] GraphFuzz: loading trees from cache...
[*] After validation: total scopes: 4
[*] After validation: usable scopes: 4
INFO: found LLVMFuzzerCustomMutator (0x563bbf). Disabling -len_control by default.
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 1797462339
INFO: Loaded 1 modules   (136 inline 8-bit counters): 136 [0x65b578, 0x65b600),
INFO: Loaded 1 PC tables (136 PCs): 136 [0x5eefb0,0x5ef830),
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 4096 bytes
INFO: A corpus is not provided, starting from an empty corpus
#2	INITED cov: 1 ft: 1 corp: 1/1b exec/s: 0 rss: 33Mb
	NEW_FUNC[1/54]: 0x55a980 in shim_finalize (/harness/in/fuzz_exec+0x55a980)
	NEW_FUNC[2/54]: 0x55ae60 in shim_2 (/harness/in/fuzz_exec+0x55ae60)
#3	NEW    cov: 69 ft: 70 corp: 2/28b lim: 4096 exec/s: 0 rss: 35Mb L: 27/27 MS: 1 CustomCrossOver-
#8	REDUCE cov: 69 ft: 70 corp: 2/19b lim: 4096 exec/s: 0 rss: 36Mb L: 18/18 MS: 5 Custom-Custom-Custom-Custom-CustomCrossOver-
#32768	pulse  cov: 69 ft: 70 corp: 2/19b lim: 4096 exec/s: 16384 rss: 256Mb
#65536	pulse  cov: 69 ft: 70 corp: 2/19b lim: 4096 exec/s: 16384 rss: 477Mb
```

During generation, `gfuzz` will also produce a `schema.json` file which contains runtime metadata. This file must exist when you run the fuzzer. By default, the fuzzer assumes it is at the path `./schema.json` but you can also specify it explicitly with `./fuzz_exec --graphfuzz_schema=/path/to/schema.json`.

So if you move the `fuzz_exec` executable, just be sure to also move the generated `schema.json` so the fuzzer can run.

Please let me know if this helps with your problem!

Also currently this error message is very confusing, so I will add a few checks to catch some cases where the schema.json file doesn't exist.

**Comment by CodeLogicError** [comment]
i can't recover the bug ,it's run well. If I see the bug again , I will reserve the enviroment.
