### ISSUE TITLE
Interleaved output of fuzz_write.cpp

### ISSUE THREAD

**Issue by NikLeberg** [hgarrereyn/GraphFuzz#8]
Hi there.

I noticed, that when converting the graph to the code representation with `./fuzz_write`, informal output from `schema.hpp` is also present in the output:

```
[*] Loading: schema.json
[*] GraphFuzz: loading trees from cache...
[*] After validation: total scopes: 5
[*] After validation: usable scopes: 5
```
I tried to create a usable `crash.cpp` with: `./fuzz_write crash-<hash> | tee crash.cpp`

My solution was to replace `std::cout` with `std::cerr` at the relevant places in schema.hpp. As such one can redirect only stdout to a file and it is free from other output. This works because libFuzzer seems to only print to stderr as well.

If such changes are of interest, I'll happily create a pull request.

Thank you again very much for this excellent project!

Kind regards
Niklaus

**Comment by hgarrereyn** [comment]
Hey, that's a great idea! It would definitely make it easier to automate the code generation and replay process. I'll definitely merge this PR if you submit one!
